<a href="https://colab.research.google.com/github/felindabitrus-arch/Felinda-/blob/Felindabitrus/Copy_of_WEEK_6_Pandas_for_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# 📘 ASSIGNMENT (Week 6)

Using Pandas:

1. Create a new CSV file with at least 10 students.
2. Load the CSV using pd.read_csv().
3. Compute:
   - Subject averages
   - Overall student averages
4. Identify:
   - Top performing student
   - Lowest performing student
5. Export the updated dataset to a new CSV file.

Submit your completed notebook (.ipynb).

In [ ]:

data = {
    "Name": ["Felinda", "Angel", "Samuel", "Faith", "Titus", "Judge", "David", "Samuel", "Grace", " John"],
    "Math": [65, 80, 45, 90, 75, 60, 70, 80, 85, 90],
    "English": [70, 85, 50, 88, 60, 50, 55, 65, 70, 80],
    "chemistry": [72, 78, 48, 50, 80, 85, 63, 75, 92, 79]
}

df = pd.DataFrame(data)
df

      Name  Math  English  chemistry
0  Felinda    65       70         72
1    Angel    80       85         78
2   Samuel    45       50         48
3    Faith    90       88         50
4    Titus    75       60         80
5    Judge    60       50         85
6    David    70       55         63
7   Samuel    80       65         75
8    Grace    85       70         92
9     John    90       80         79

In [ ]:
df = pd.read_csv("students.csv")
df

      Name  Math  English  chemistry
0  Felinda    65       70         72
1    Angel    80       85         78
2   Samuel    45       50         48
3    Faith    90       88         50
4    Titus    75       60         80
5    Judge    60       50         85
6    David    70       55         63
7   Samuel    80       65         75
8    Grace    85       70         92
9     John    90       80         79

In [ ]:

df[["Math", "English", "chemistry"]].mean()

Math         74.0
English      67.3
chemistry    72.2
dtype: float64

In [ ]:

df["Average"] = df[["Math", "English", "chemistry"]].mean(axis=1)
df

      Name  Math  English  chemistry    Average
0  Felinda    65       70         72  69.000000
1    Angel    80       85         78  81.000000
2   Samuel    45       50         48  47.666667
3    Faith    90       88         50  76.000000
4    Titus    75       60         80  71.666667
5    Judge    60       50         85  65.000000
6    David    70       55         63  62.666667
7   Samuel    80       65         75  73.333333
8    Grace    85       70         92  82.333333
9     John    90       80         79  83.000000

In [ ]:
df["Average"] = df[["Math", "English", "chemistry"]].mean(axis=1)

top_student = df.loc[df["Average"].idxmax()]

print("Top Performing Student:")
print(top_student)

Top Performing Student:
Name          John
Math            90
English         80
chemistry       79
Average       83.0
Name: 9, dtype: object

In [ ]:
lowest_student = df.loc[df["Average"].idxmin()]

print("Lowest Performing Student:")
print(lowest_student)

Lowest Performing Student:
Name            Samuel
Math                45
English             50
chemistry           48
Average      47.666667
Name: 2, dtype: object

FELINDA BITRUS
UJ/2025/CP/0258
DATA SCIENCE